packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "argon2"
  - "esbuild"
  - "prisma"
  - "sharp"
  - "bcrypt"
allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  argon2: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
